/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lzl;

import java.awt.Font;
import java.awt.Rectangle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author liangzl2
 */
public class AnsysView extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private DataOfAnsys doa;
    private final AnsysController ac;
    private Object[] keyset;
    private DefaultListModel dlm;
    /**
     * Creates new form AnsysView
     */
    public AnsysView() {
        initComponents();
        ac=new AnsysController(jProgressBar1);
        doa=null;
        
        
        dlm=new DefaultListModel();
        int listrowheight = this.jList1.getHeight();
        dlm.addElement("row 0");
        
        this.jList1.setModel(dlm);
        Rectangle rct=this.jList1.getCellBounds(0, 0);
        System.out.println("rct=="+rct.toString());
        int cellheight=rct.height;
        int cellnum = listrowheight/cellheight;
        for(int i=1;i<cellnum;i++){
            dlm.addElement("row"+i);
        }
        DefaultTableModel dtm;
        String[] colname={"Node",
               "SX",
               "SY",
               "SZ",
               "SXY",
               "SYZ",
               "SXZ"};
        dtm=new DefaultTableModel(colname, 8);
        this.jTable1.setModel(dtm);
        Font af=new Font("Arial",Font.PLAIN,20);
        this.jTable1.setFont(af);
        this.jTable1.setRowHeight(af.getSize()+2);
        
        this.jSlider1.setEnabled(false);

        this.jSlider1.addChangeListener((ChangeEvent ce) -> {
            if (keyset != null) {
                Object o = keyset[jSlider1.getValue()];
                jTextField1.setText(o.toString());
                getAndSetElement(Integer.valueOf(o.toString()));
            }
        });
        
        
        this.jList1.addListSelectionListener((l)->{
            try{
                System.out.println("first:"+l.getFirstIndex()+
                        " last:"+l.getLastIndex()+
                        " valueIsAdjust:"+l.getValueIsAdjusting()+
                        " firstEle:"+jList1.getModel().getElementAt(l.getFirstIndex())+
                        " lastEle:"+jList1.getModel().getElementAt(l.getLastIndex())
                );
                String s = jList1.getModel().getElementAt(l.getLastIndex());
                getAndSetElement(Integer.valueOf(s));
                this.jTextField1.setText(s);
            }catch(ArrayIndexOutOfBoundsException e){
                
            }
            
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("100");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("搜索");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("加载模型");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jProgressBar1.setValue(50);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Thread(()->{
            SwingUtilities.invokeLater(() -> {
                this.jButton2.setEnabled(false);
            });
            
            try {
                
                doa = ac.readAnsysFile("D:\\!CPP\\0405opening\\PRESOL.lis");
            } catch (IOException ex) {
                Logger.getLogger(AnsysView.class.getName()).log(Level.SEVERE, null, ex);
            }
            SwingUtilities.invokeLater(() -> {
                this.jProgressBar1.setValue(100);
                this.jSlider1.setMaximum(this.doa.elementlist.size()-1);
                this.jButton2.setEnabled(true);
                this.jSlider1.setEnabled(true);
                dlm.removeAllElements();
                this.doa.elementlist.keySet().forEach((key)->{
                    dlm.addElement(key.toString());
                });
                keyset = this.doa.elementlist.keySet().toArray();
            });
        }).start();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try{
            int element=Integer.valueOf(this.jTextField1.getText());
            if(getAndSetElement(element)){
                
            }else{
                this.jTextField1.setText("Null!");
            }
        }catch(NumberFormatException ne){
            this.jTextField1.setText("Invalid input! should be num");
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int element=Integer.valueOf(this.jTextField1.getText());
            if(getAndSetElement(element)){
                
            }else{
                this.jTextField1.setText("Null!");
            }
        }catch(NumberFormatException ne){
            this.jTextField1.setText("Invalid input! should be num");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean getAndSetElement(int elenum){
        if (this.doa != null) {
            Element e = doa.elementlist.get(elenum);
            if (e != null) {
                int[] nodes = e.node;
                TableModel tm = this.jTable1.getModel();
                for (int j = 0; j < nodes.length; j++) {
                    Node n = doa.nodelist.get(nodes[j]);

                    tm.setValueAt(n.nodenum, j, 0);
                    tm.setValueAt(n.SX, j, 1);
                    tm.setValueAt(n.SY, j, 2);
                    tm.setValueAt(n.SZ, j, 3);
                    tm.setValueAt(n.SXY, j, 4);
                    tm.setValueAt(n.SYZ, j, 5);
                    tm.setValueAt(n.SXZ, j, 6);

                }
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
